### ISSUE TITLE
I want to avoid duplicate logins.

### ISSUE THREAD

**Issue by swy0710** [adamint/spotify-web-api-kotlin#292]
I am trying to authenticate using pkce, but for that, it says that I have to inherit AbstractSpotifyPkceLoginActivity. If I inherit and execute AbstractSpotifyPkceLoginActivity, the activity for login is executed even if I am already logged in in the spotify app. Are there any ways to make them work together? (meaning that I want to skip login if i am already logged in in the spotify app)

**Comment by adamint** [comment]
I responded on Discord as well, but for others that run into this issue:
PKCE auth is incompatible with Spotify SSO (sign-on using the app). This is what you should use implicit auth for. 
The reason why PKCE auth is typically recommended is that it doesn't rely on installation of the Spotify app, and so token handling and refresh is done entirely within the context of your app. But... when convenience is a relevant concern, that's why the library wraps the spotify-auth library :)

**Comment by swy0710** [comment]
Thank you for quick response. 
Let me use implicit auth.
